version: '3.9'
services:
  flights-api:
    build:
      context: .
      dockerfile: infra/local/app/Dockerfile
      target: api
    command: server -c /conf/config.yaml
    restart: unless-stopped
    volumes:
      - ./config.yaml:/conf/config.yaml
    ports:
      - "8080:8080"
volumes:
  feeds-ch-volume:
    driver: local